import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TradeStoreProvider } from "./store/TradeStore";
import { WatchlistProvider } from "./store/WatchlistContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <TradeStoreProvider>
          <WatchlistProvider>
            <div className="flex min-h-screen items-center justify-center bg-zinc-50 font-sans dark:bg-black">
              {children}
            </div>
          </WatchlistProvider>
        </TradeStoreProvider>
      </body>
    </html>
  );
}
